export default {
  projects: [{
    id: 1,
    name: "高精度电子地图产业化开发（一期）",
    status: "green"
  }, {
  	id: 2,
  	name: "Mobileye合作REM项目(POC阶段)",
  	status: "yellow"
  }],
  monthlyTasks: [{
    id: 1,
    status: "red",
    month: "2018-4",
    projectId: 1
  }, {
    id: 2,
    status: "green",
    month: "2018-5",
    projectId: 1
  }, {
    id: 3,
    status: "green",
    month: "2018-6",
    projectId: 1
  }, {
    id: 4,
    status: "green",
    month: "2018-7",
    projectId: 1
  }, {
    id: 5,
    status: "red",
    month: "2018-8",
    projectId: 1
  }, {
    id: 6,
    status: "green",
    month: "2018-9",
    projectId: 1
  }, {
    id: 7,
    status: "green",
    month: "2018-10",
    projectId: 1
  }, {
    id: 8,
    status: "red",
    month: "2018-11",
    projectId: 1
  }, {
    id: 9,
    status: "red",
    month: "2018-12",
    projectId: 1
  }, {
    id: 10,
    status: "",
    month: "2019-1",
    projectId: 1
  }, {
    id: 11,
    status: "",
    month: "2019-2",
    projectId: 1
  }, {
    id: 12,
    status: "",
    month: "2019-3",
    projectId: 1
  }, {
    id: 13,
    status: "green",
    month: "2018-4",
    projectId: 2
  }, {
    id: 14,
    status: "green",
    month: "2018-5",
    projectId: 2
  }, {
    id: 15,
    status: "green",
    month: "2018-6",
    projectId: 2
  }, {
    id: 16,
    status: "green",
    month: "2018-7",
    projectId: 2
  }, {
    id: 17,
    status: "green",
    month: "2018-8",
    projectId: 2
  }, {
    id: 18,
    status: "green",
    month: "2018-9",
    projectId: 2
  }, {
    id: 19,
    status: "green",
    month: "2018-10",
    projectId: 2
  }, {
    id: 20,
    status: "green",
    month: "2018-11",
    projectId: 2
  }, {
    id: 21,
    status: "red",
    month: "2018-12",
    projectId: 2
  }, {
    id: 22,
    status: "",
    month: "2019-1",
    projectId: 2
  }, {
    id: 23,
    status: "",
    month: "2019-2",
    projectId: 2
  }, {
    id: 24,
    status: "",
    month: "2019-3",
    projectId: 2
  }],
  taskItems: [{
    id: 1,
    name: "项目启动",
    taskId: 1
  }, {
    id: 2,
    name: "提供地图传感器第二版",
    taskId: 2
  }, {
    id: 3,
    name: "地图众包系统demo演示",
    taskId: 2
  }, {
    id: 4,
    name: "完成地图众包更新云端系统开发",
    taskId: 4
  }, {
    id: 5,
    name: "三千公里交付",
    taskId: 5
  }, {
    id: 6,
    name: "提供地图传感器第三版",
    taskId: 5
  }, {
    id: 7,
    name: "完成众包更新系统产线平台开发",
    taskId: 5
  }, {
    id: 8,
    name: "提供地图传感器R版",
    taskId: 6
  }, {
    id: 9,
    name: "实现云端、管端、车端闭环测试",
    taskId: 6
  }, {
    id: 10,
    name: "八千公里交付",
    taskId: 8
  }, {
    id: 11,
    name: "提供地图传感器2.0R版",
    taskId: 8
  }, {
    id: 12,
    name: "完善地图众包更新系统并最终交付",
    taskId: 8
  }, {
    id: 13,
    name: "一万公里交付",
    taskId: 9
  }, {
    id: 14,
    name: "完成POC阶段合同签订",
    taskId: 19
  }, {
    id: 15,
    name: "完成POC阶段数据采集",
    taskId: 20
  }, {
    id: 16,
    name: "完成POC阶段数据验收",
    taskId: 21
  }]
}
